// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijurjouxmkitrfiykzuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdXJqb3V4bWtpdHJmaXlrenV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDI2NjIsImV4cCI6MjA2OTg3ODY2Mn0.xRRw-CBQtzN1iqGIBIqS9TJ885Fp0Bna0MjX4HQu-1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});